---
title: "CPI Index"
author: "Igor Morzan"
date: "4/5/2019"
output: html_document
---

```{r setup, include=FALSE}
# loads the necessary libraries
library(jsonlite)
library(tidyverse)
library(ggplot2)

# downloads in the json file containing the data from the website
json_file <- 'https://datahub.io/core/corruption-perceptions-index/datapackage.json'
json_data <- fromJSON(paste(readLines(json_file), collapse=""))

# get lists of all resources within the dataset
print(json_data$resources$name)

# this code is sourced from https://datahub.io/core/corruption-perceptions-index#r in order to 
# integrate it into R and be able to read it

# for loop to iterate through all the values in the dataset
for(i in 1:length(json_data$resources$datahub$type)){
  if(json_data$resources$datahub$type[i]=='derived/csv'){
    path_to_file = json_data$resources$path[i]
    # creates the corruption_data dataset that is referenced to create the plot
    corruption_data <- read.csv(url(path_to_file))
    # prints out tabular data
    print(corruption_data)
  }
}

knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
corruption_data %>%
  # filters for Latin American countries
  filter(Jurisdiction %in% c("Argentina", "Bolivia", "Brazil", "Chile", "Colombia",
                             "Ecuador", "Paraguay", "Peru", "Uruguay", "Venezuela")) %>%
  # sets the X axis to the countries and y axis to data from 2015
  ggplot(aes(x = Jurisdiction, y = X2015)) +
  geom_point() +
  labs(title = "Latin American Countries' Corruption Perceptions Index for 2015", 
       subtitle = "Measures the degree that corruption is percieved, with higher values representing less corruption",
       caption = "Source: Transparency International") +
  xlab(NULL) +
  ylab("Corruption Perceptions Index")
```
